# Generated by Django 5.1.5 on 2025-01-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("house_no", models.CharField(max_length=10)),
                ("occupation", models.CharField(max_length=50)),
                ("business", models.CharField(blank=True, max_length=50, null=True)),
                ("no_of_children", models.IntegerField(default=0)),
            ],
        ),
    ]
