# Generated by Django 5.1.5 on 2025-01-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("residents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resident",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name="resident",
            table="residents",
        ),
    ]
